// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxpafVruCfNW7tkxXYa8MS8_jl9ikdPA',
    appId: '1:701402225227:web:deae24f6a72ffda52a8bce',
    messagingSenderId: '701402225227',
    projectId: 'beta-17f9f',
    authDomain: 'beta-17f9f.firebaseapp.com',
    storageBucket: 'beta-17f9f.appspot.com',
    measurementId: 'G-KTK7NRTG6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jajhEkMNMH-4Q_9gao-IljKJyWGM-1c',
    appId: '1:701402225227:android:e8bd9c6d95f9d0e02a8bce',
    messagingSenderId: '701402225227',
    projectId: 'beta-17f9f',
    storageBucket: 'beta-17f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5lykWFfclS9QXw7lhnBFrx4ZVr3bw_g',
    appId: '1:701402225227:ios:f4c19bb256c0954e2a8bce',
    messagingSenderId: '701402225227',
    projectId: 'beta-17f9f',
    storageBucket: 'beta-17f9f.appspot.com',
    iosClientId: '701402225227-d2lhb70mjm8p1b7jtbieqllelu18aond.apps.googleusercontent.com',
    iosBundleId: 'com.example.bam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5lykWFfclS9QXw7lhnBFrx4ZVr3bw_g',
    appId: '1:701402225227:ios:d9564b6e2ef538012a8bce',
    messagingSenderId: '701402225227',
    projectId: 'beta-17f9f',
    storageBucket: 'beta-17f9f.appspot.com',
    iosClientId: '701402225227-od27hmiquiji2krb8iqpi0houlj4t9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bam.RunnerTests',
  );
}
